<a href="https://colab.research.google.com/github/ShreshthaPandey/JOSAA-collage-predictor/blob/main/clg_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
import zipfile

with zipfile.ZipFile("/content/archive (13).zip", "r") as zip_ref:
    zip_ref.extractall("dataset")

In [ ]:
import os

for year in range(2016, 2020):
    for round in range(1, 6):

        file = f"dataset/{year}_round_{round}.csv"

        if os.path.exists(file):
            os.remove(file)

In [ ]:
import os

files = os.listdir("dataset")
files

['2020_round_2.csv',
 '2023_round_3.csv',
 '2022_round_5.csv',
 '2020_round_1.csv',
 '2025_round_3.csv',
 '2023_round_6.csv',
 '2021_round_3.csv',
 '2022_round_6.csv',
 '2025_round_2.csv',
 '2023_round_4.csv',
 '2025_round_6.csv',
 '2023_round_1.csv',
 '2025_round_1.csv',
 '2023_round_2.csv',
 '2025_round_5.csv',
 '2022_round_1.csv',
 '2022_round_2.csv',
 '2021_round_2.csv',
 '2024_round_5.csv',
 '2020_round_3.csv',
 '2022_round_3.csv',
 '2024_round_3.csv',
 '2024_round_1.csv',
 '2024_round_2.csv',
 '2026_round_1.csv',
 '2020_round_5.csv',
 '2022_round_4.csv',
 '2021_round_5.csv',
 '2021_round_6.csv',
 '2023_round_5.csv',
 '2020_round_6.csv',
 '2024_round_4.csv',
 '2021_round_4.csv',
 '2021_round_1.csv',
 '2020_round_4.csv',
 '2025_round_4.csv',
 'jee_exam_dynamics.csv']

In [ ]:
df = pd.read_csv("dataset/jee_exam_dynamics.csv")
df

    Year Number_of_JEE_applicants_registered  Total_number_of_seats
0   2026                           15,38,468                  67323
1   2025                           14,75,103                  62853
2   2024                           14,15,110                  57152
3   2023                           11,62,398                  56874
4   2022                           10,26,799                  54477
5   2021                           10,48,012                  52453
6   2020                           11,74,103                  50822
7   2019                           12,37,892                  45235
8   2018                           11,35,084                  37473
9   2017                           11,86,454                  36268
10  2016                           12,07,257                  34871

In [ ]:
df.drop([7 , 8 , 9 , 10])

   Year Number_of_JEE_applicants_registered  Total_number_of_seats
0  2026                           15,38,468                  67323
1  2025                           14,75,103                  62853
2  2024                           14,15,110                  57152
3  2023                           11,62,398                  56874
4  2022                           10,26,799                  54477
5  2021                           10,48,012                  52453
6  2020                           11,74,103                  50822

In [ ]:
del list

In [ ]:
import os
import pandas as pd

for file in os.listdir("dataset"):
    if file.endswith(".csv"):

        path = os.path.join("dataset", file)
        df = pd.read_csv(path)

        print("\nFile:", file)
        print("Rows:", len(df))
        print("Columns:", list(df.columns))

File: 2020_round_2.csv
Rows: 9138
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2023_round_3.csv
Rows: 10404
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2022_round_5.csv
Rows: 9764
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2020_round_1.csv
Rows: 9338
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2025_round_3.csv
Rows: 11982
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2023_round_6.csv
Rows: 10366
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2021_round_3.csv
Rows: 9239
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2022_round_6.csv
Rows: 9733
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2025_round_2.csv
Rows: 12047
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2023_round_4.csv
Rows: 10392
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2025_round_6.csv
Rows: 11945
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2023_round_1.csv
Rows: 10843
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2025_round_1.csv
Rows: 12275
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2023_round_2.csv
Rows: 10475
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2025_round_5.csv
Rows: 11966
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2022_round_1.csv
Rows: 10023
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2022_round_2.csv
Rows: 9817
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2021_round_2.csv
Rows: 9268
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2024_round_5.csv
Rows: 11262
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2020_round_3.csv
Rows: 9069
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2022_round_3.csv
Rows: 9774
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2024_round_3.csv
Rows: 11308
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2024_round_1.csv
Rows: 11688
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2024_round_2.csv
Rows: 11378
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2026_round_1.csv
Rows: 13292
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2020_round_5.csv
Rows: 9033
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2022_round_4.csv
Rows: 9769
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2021_round_5.csv
Rows: 9224
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2021_round_6.csv
Rows: 9179
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2023_round_5.csv
Rows: 10385
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2020_round_6.csv
Rows: 8991
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2024_round_4.csv
Rows: 11282
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2021_round_4.csv
Rows: 9230
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2021_round_1.csv
Rows: 9450
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2020_round_4.csv
Rows: 9045
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: 2025_round_4.csv
Rows: 11974
Columns: ['Institute', 'Academic Program Name', 'Quota', 'Seat Type', 'Gender', 'Opening Rank', 'Closing Rank']

File: jee_exam_dynamics.csv
Rows: 11
Columns: ['Year', 'Number_of_JEE_applicants_registered', 'Total_number_of_seats']

In [ ]:
import os
import pandas as pd

years = range(2020, 2027)

for year in years:
    all_data = []

    for file in os.listdir("dataset"):
        if file.startswith(f"{year}_round_") and file.endswith(".csv"):

            path = os.path.join("dataset", file)
            df = pd.read_csv(path)

            # Round number extract karo
            round_no = file.split("_")[2].replace(".csv", "")

            # New column
            df["round"] = round_no

            all_data.append(df)

    # Saare rounds merge
    if all_data:
        merged_df = pd.concat(all_data, ignore_index=True)

        # Save
        merged_df.to_csv(f"dataset/{year}.csv", index=False)

        print(f"{year}: {len(merged_df)} rows")

2020: 54614 rows
2021: 55590 rows
2022: 58880 rows
2023: 62865 rows
2024: 56918 rows
2025: 72189 rows
2026: 13292 rows

In [ ]:
df0 = pd.read_csv("dataset/2020.csv")
df1 = pd.read_csv("dataset/2021.csv")
df2 = pd.read_csv("dataset/2022.csv")
df3 = pd.read_csv("dataset/2023.csv")
df3 = pd.read_csv("dataset/2024.csv")
df5 = pd.read_csv("dataset/2025.csv")
df6 = pd.read_csv("dataset/2026.csv")

/tmp/ipykernel_3006/917474916.py:6: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df5 = pd.read_csv("dataset/2025.csv")

In [ ]:
df0.head()

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,round
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Gender-Neutral,7182,9202,2
1,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Female-only (including Supernumerary),13212,15064,2
2,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN (PwD),Gender-Neutral,56P,56P,2
3,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Gender-Neutral,1297,1589,2
4,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Female-only (including Supernumerary),2655,2819,2

In [ ]:
df0.groupby("round").size()

round
1    9338
2    9138
3    9069
4    9045
5    9033
6    8991
dtype: int64

In [ ]:
import pandas as pd

all_data = []

for year in range(2020, 2027):
    file = f"dataset/{year}.csv"

    df = pd.read_csv(file)

    # Year column add karo
    df["year"] = year

    all_data.append(df)

# All years merge
final_df = pd.concat(all_data, ignore_index=True)

print(final_df.shape)
final_df.head()

(374348, 9)

/tmp/ipykernel_3006/812342895.py:8: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,round,year
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Gender-Neutral,7182,9202,2,2020
1,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Female-only (including Supernumerary),13212,15064,2,2020
2,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN (PwD),Gender-Neutral,56P,56P,2,2020
3,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Gender-Neutral,1297,1589,2,2020
4,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Female-only (including Supernumerary),2655,2819,2,2020

In [ ]:
final_df.describe()

               round           year
count  374313.000000  374313.000000
mean        3.319642    2022.752317
std         1.707685       1.801648
min         1.000000    2020.000000
25%         2.000000    2021.000000
50%         3.000000    2023.000000
75%         5.000000    2024.000000
max         6.000000    2026.000000

In [ ]:
final_df.isnull().sum()

Institute                35
Academic Program Name    35
Quota                    35
Seat Type                35
Gender                   35
Opening Rank             35
Closing Rank             35
round                     0
year                      0
dtype: int64

In [ ]:
final_df[final_df["Academic Program Name"].isnull()]
final_df = final_df.dropna()

In [ ]:
final_df.isnull().sum()

Institute                0
Academic Program Name    0
Quota                    0
Seat Type                0
Gender                   0
Opening Rank             0
Closing Rank             0
round                    0
year                     0
dtype: int64

In [ ]:
final_df.shape

(374313, 9)

In [ ]:
final_df.duplicated().sum()

np.int64(0)

In [ ]:
df = final_df

In [ ]:
df.shape

(330088, 9)

In [ ]:
df.head(1)

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,round,year
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Gender-Neutral,7182,9202,2,2020

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 330088 entries, 0 to 374347
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Institute              330088 non-null  object
 1   Academic Program Name  330088 non-null  object
 2   Quota                  330088 non-null  object
 3   Seat Type              330088 non-null  object
 4   Gender                 330088 non-null  object
 5   Opening Rank           330088 non-null  int32
 6   Closing Rank           330088 non-null  int32
 7   round                  330088 non-null  int16
 8   year                   330088 non-null  int16
dtypes: int16(2), int32(2), object(5)
memory usage: 18.9+ MB

In [ ]:
df.describe()

        Opening Rank   Closing Rank          round           year
count  330088.000000  330088.000000  330088.000000  330088.000000
mean     5555.379623    6585.660624       3.307633    2022.756380
std      6024.143701    7092.578519       1.707922       1.797935
min         1.000000       1.000000       1.000000    2020.000000
25%      1135.000000    1373.000000       2.000000    2021.000000
50%      3328.000000    3934.000000       3.000000    2023.000000
75%      7944.000000    9224.000000       5.000000    2024.000000
max     32752.000000   32752.000000       6.000000    2026.000000

In [ ]:
df.groupby('Opening Rank').size()

Opening Rank
1        211
2        158
3        207
4        182
5        194
        ...
32672      1
32688      2
32704      1
32720      6
32752      7
Length: 6117, dtype: int64

In [ ]:
df.sort_values(by='Opening Rank' , ascending=False)

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,round,year
265749,"Puducherry Technological University, Puducherry","Mechatronics Engineering (4 Years, Bachelor of...",HS,SC,Gender-Neutral,32752,32752,1,2024
369780,"National Institute of Technology, Uttarakhand","Civil Engineering (4 Years, Bachelor of Techno...",HS,OBC-NCL,Female-only (including Supernumerary),32752,32752,1,2026
254101,"Puducherry Technological University, Puducherry","Mechatronics Engineering (4 Years, Bachelor of...",HS,SC,Gender-Neutral,32752,32752,3,2024
288451,"Puducherry Technological University, Puducherry","Mechatronics Engineering (4 Years, Bachelor of...",HS,SC,Gender-Neutral,32752,32752,4,2024
305615,National Institute of Technology Durgapur,"Biotechnology (5 Years, Bachelor and Master of...",HS,OPEN,Gender-Neutral,32752,32752,2,2025
...,...,...,...,...,...,...,...,...,...
243349,Indian Institute of Technology Bombay,"Computer Science and Engineering (4 Years, Bac...",AI,OPEN (PwD),Gender-Neutral,1,3,3,2024
220983,"School of Planning & Architecture, New Delhi","Architecture (5 Years, Bachelor of Architecture)",AI,ST,Gender-Neutral,1,24,2,2023
119589,"School of Planning & Architecture, New Delhi","Architecture (5 Years, Bachelor of Architecture)",AI,ST (PwD),Gender-Neutral,1,1,5,2022
211285,Indian Institute of Technology Bombay,"Computer Science and Engineering (4 Years, Bac...",AI,OPEN,Gender-Neutral,1,67,2,2023
361205,Indian Institute of Technology Bombay,"Computer Science and Engineering (4 Years, Bac...",AI,OPEN (PwD),Gender-Neutral,1,6,1,2026

In [ ]:
# df[df['Opening Rank'] == '99P']
df = df[
    ~(
        df["Opening Rank"].astype(str).str.contains("P", na=False) |
        df["Closing Rank"].astype(str).str.contains("P", na=False)
    )
]

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,round,year
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Gender-Neutral,7184,9200,2,2020
1,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Female-only (including Supernumerary),13216,15064,2,2020
3,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Gender-Neutral,1297,1589,2,2020
4,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Female-only (including Supernumerary),2656,2820,2,2020
5,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OBC-NCL,Gender-Neutral,3056,3824,2,2020
...,...,...,...,...,...,...,...,...,...
374343,"Central University of Punjab, Bathinda","Computer Science and Engineering (4 Years, Bac...",AI,OPEN (PwD),Gender-Neutral,3240,3250,1,2026
374344,"Central University of Punjab, Bathinda","Computer Science and Engineering (4 Years, Bac...",AI,EWS,Gender-Neutral,9504,9744,1,2026
374345,"Central University of Punjab, Bathinda","Computer Science and Engineering (4 Years, Bac...",AI,OBC-NCL,Gender-Neutral,20304,22288,1,2026
374346,"Central University of Punjab, Bathinda","Computer Science and Engineering (4 Years, Bac...",AI,SC,Gender-Neutral,7784,10736,1,2026
374347,"Central University of Punjab, Bathinda","Computer Science and Engineering (4 Years, Bac...",AI,ST,Gender-Neutral,4988,5056,1,2026

In [ ]:
df.sort_values("Opening Rank", ascending=False)

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,round,year
265749,"Puducherry Technological University, Puducherry","Mechatronics Engineering (4 Years, Bachelor of...",HS,SC,Gender-Neutral,32752,32752,1,2024
369780,"National Institute of Technology, Uttarakhand","Civil Engineering (4 Years, Bachelor of Techno...",HS,OBC-NCL,Female-only (including Supernumerary),32752,32752,1,2026
254101,"Puducherry Technological University, Puducherry","Mechatronics Engineering (4 Years, Bachelor of...",HS,SC,Gender-Neutral,32752,32752,3,2024
288451,"Puducherry Technological University, Puducherry","Mechatronics Engineering (4 Years, Bachelor of...",HS,SC,Gender-Neutral,32752,32752,4,2024
305615,National Institute of Technology Durgapur,"Biotechnology (5 Years, Bachelor and Master of...",HS,OPEN,Gender-Neutral,32752,32752,2,2025
...,...,...,...,...,...,...,...,...,...
243349,Indian Institute of Technology Bombay,"Computer Science and Engineering (4 Years, Bac...",AI,OPEN (PwD),Gender-Neutral,1,3,3,2024
220983,"School of Planning & Architecture, New Delhi","Architecture (5 Years, Bachelor of Architecture)",AI,ST,Gender-Neutral,1,24,2,2023
119589,"School of Planning & Architecture, New Delhi","Architecture (5 Years, Bachelor of Architecture)",AI,ST (PwD),Gender-Neutral,1,1,5,2022
211285,Indian Institute of Technology Bombay,"Computer Science and Engineering (4 Years, Bac...",AI,OPEN,Gender-Neutral,1,67,2,2023
361205,Indian Institute of Technology Bombay,"Computer Science and Engineering (4 Years, Bac...",AI,OPEN (PwD),Gender-Neutral,1,6,1,2026

In [ ]:
print("Opening Rank NaN:", df["Opening Rank"].isna().sum())
print("Closing Rank NaN:", df["Closing Rank"].isna().sum())

print("Opening Rank inf:", np.isinf(df["Opening Rank"]).sum())
print("Closing Rank inf:", np.isinf(df["Closing Rank"]).sum())

Opening Rank NaN: 0
Closing Rank NaN: 0
Opening Rank inf: 0
Closing Rank inf: 0

In [ ]:
df = df[~(np.isinf(df["Closing Rank"]))]
df = df[~(np.isinf(df["Opening Rank"]))]

In [ ]:
df["Opening Rank"] = df["Opening Rank"].astype('int32')
df["Closing Rank"] = df["Closing Rank"].astype('int32')
df['round'] = df['round'].astype('int16')
df['year'] = df['year'].astype('int16')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 330088 entries, 0 to 374347
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Institute              330088 non-null  object
 1   Academic Program Name  330088 non-null  object
 2   Quota                  330088 non-null  object
 3   Seat Type              330088 non-null  object
 4   Gender                 330088 non-null  object
 5   Opening Rank           330088 non-null  int32
 6   Closing Rank           330088 non-null  int32
 7   round                  330088 non-null  int16
 8   year                   330088 non-null  int16
dtypes: int16(2), int32(2), object(5)
memory usage: 18.9+ MB

In [ ]:
df.shape

(330088, 9)

In [ ]:
df.groupby("Opening Rank").size()

Opening Rank
1        211
2        158
3        207
4        182
5        194
        ...
32672      1
32688      2
32704      1
32720      6
32752      7
Length: 6117, dtype: int64

In [ ]:
df.groupby("Quota").size()

Quota
AI     6235
GO       37
HS     3291
JK       80
LA       14
OS     3635
dtype: int64

In [ ]:
df.groupby("Institute").size().sort_values(ascending=False)

Institute
National Institute of Technology, Rourkela                                          406
National Institute of Technology, Kurukshetra                                       360
National Institute of Technology, Warangal                                          339
National Institute of Technology Patna                                              333
Dr. B R Ambedkar National Institute of Technology, Jalandhar                        316
                                                                                   ...
National Institute of Electronics and Information Technology, Agartala                7
National Institute of Food Technology Entrepreneurship and Management, Thanjavur      7
National Institute of Electronics and Information Technology, Imphal                  6
National Institute of Electronics and Information Technology, Kohima                  6
National Institute of Electronics and Information Technology, Calicut                 6
Length: 138, dtype: int64

In [ ]:
df['Opening Rank'] = df['Opening Rank'].astype('int32')
df['Closing Rank'] = df['Closing Rank'].astype('int32')

In [ ]:
max_iit_crl = df[(df['Seat Type'] == 'OPEN') & (df['Quota'] == 'AI')]['Closing Rank'].max()
print("Max IIT CRL:", max_iit_crl)

# Max CRL Rank for NITs/IIITs/GFTIs (Home State and Other State Quotas)
max_nit_crl = df[(df['Seat Type'] == 'OPEN') & (df['Quota'].isin(['HS', 'OS']))]['Closing Rank'].max()
print("Max NIT/IIIT CRL:", max_nit_crl)

Max IIT CRL: 32752
Max NIT/IIIT CRL: 32752

In [ ]:
df.describe()

        Opening Rank   Closing Rank          round           year
count  330088.000000  330088.000000  330088.000000  330088.000000
mean     5555.379623    6585.660624       3.307633    2022.756380
std      6024.143701    7092.578519       1.707922       1.797935
min         1.000000       1.000000       1.000000    2020.000000
25%      1135.000000    1373.000000       2.000000    2021.000000
50%      3328.000000    3934.000000       3.000000    2023.000000
75%      7944.000000    9224.000000       5.000000    2024.000000
max     32752.000000   32752.000000       6.000000    2026.000000

Your predictor works for    →  Ranks 1 to ~40,000

Students above rank 40,000  →  "No JoSAA colleges available"

                               You can show this message to them

In [ ]:
df[df['Opening Rank'] < 0]

Empty DataFrame
Columns: [Institute, Academic Program Name, Quota, Seat Type, Gender, Opening Rank, Closing Rank, round, year]
Index: []

In [ ]:

df = df[df['Closing Rank'] > 0]
df = df[df['Opening Rank'] > 0]

In [ ]:
# Check if any opening rank > closing rank (data error)
bad_rows = df[df['Opening Rank'] > df['Closing Rank']]
print(f"Bad rows: {len(bad_rows)}")

Bad rows: 0

In [ ]:
df.head()

,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,round,year
0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Gender-Neutral,7184,9200,2,2020
1,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,Female-only (including Supernumerary),13216,15064,2,2020
3,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Gender-Neutral,1297,1589,2,2020
4,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,EWS,Female-only (including Supernumerary),2656,2820,2,2020
5,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OBC-NCL,Gender-Neutral,3056,3824,2,2020